---
- name: Deploy Kubernetes scripts to control plane and data plane
  hosts: all
  become: yes

  tasks:
    - name: copying master.sh to control plane
      ansible.builtin.copy:
        src: master.sh
        dest: /home/{{ ansible }}/master.sh
        mode: '0755'
      when: "'controlplane' in group_names"

    - name: copying worker.sh to data plane
      ansible.builtin.copy:
        src: worker.sh
        dest: /home/{{ ansible }}/worker.sh
        mode: '0755'
      when: "'dataplane' in group_names"

    - name: run worker.sh on data plane
      ansible.builtin.shell: /home/{{ ansible }}/worker.sh
      when: "'dataplane' in group_names"

    - name: run master.sh on control plane
      ansible.builtin.shell: /home/{{ ansible }}/master.sh
      when: "'controlplane' in group_names"